[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = ['npm ci --prefer-offline']

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npm run preview -- --host 0.0.0.0 --port ${PORT:-3000}'

[healthcheck]
path = "/"
interval = 60
timeout = 30
