[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer', 'nodejs_20']

[phases.install]
cmds = [
  'cd backend/api && composer install --no-dev --optimize-autoloader'
]

[phases.build]
cmds = [
  'cd backend/api && php artisan config:cache',
  'cd backend/api && php artisan route:cache',
  'cd backend/api && php artisan view:cache'
]

[start]
cmd = 'cd backend/api && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=${PORT:-8000}'
